### ISSUE TITLE
Default ingressClass cannot be used

### ISSUE THREAD

**Issue by jmnote** [softonic/varnish-chart#43]
Default ingressClass cannot be used.

varnish ingress (AS-IS)
https://github.com/softonic/varnish-chart/blob/0.18.6/templates/ingress.yaml#L15

```yaml
spec:
  ingressClassName: {{ .Values.ingress.className }}
```

alertmanager ingress
https://github.com/prometheus-community/helm-charts/blob/alertmanager-1.7.0/charts/alertmanager/templates/ingress.yaml#L16-L18

```yaml
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
```

prometheus ingress
https://github.com/prometheus-community/helm-charts/blob/alertmanager-1.6.0/charts/prometheus/templates/ingress.yaml#L26-L28

```yaml
spec:
  {{- if and $ingressSupportsIngressClassName .Values.server.ingress.ingressClassName }}
  ingressClassName: {{ .Values.server.ingress.ingressClassName }}
  {{- end }}
```

See also:
- https://github.com/prometheus-community/helm-charts/issues/3823
